package com.gymplatform.modules.communication;

public enum TriggerEvent {
    BIRTHDAY,
    NEW_MEMBERSHIP,
    PAYMENT_FAILED,
    PAYMENT_SUCCESS,
    APPOINTMENT_REMINDER,
    CONTRACT_EXPIRY,
    CONTRACT_CANCELLATION,
    TRIAL_BOOKED,
    MEMBERSHIP_ANNIVERSARY,
    CHECKIN_MILESTONE,
    CLASS_REMINDER,
    TRAINING_PLAN_PUBLISHED,
    WELCOME,
    CUSTOM
}
